### ISSUE TITLE
Notes on the implementation of Block assemblers.

### ISSUE THREAD

**Issue by JordiManyer** [gridap/GridapSolvers.jl#29]
Currently, there are three main problems/inconsistencies in the development of block assemblers for sparse serial/distributed FE systems: 

1. **[SOLVED] Empty blocks for distributed matrices:** Creating empty blocks for distributed matrices is not completely straightforward. This is due to ghost ids being different in the `PSparseMatrices` wrt the `DistributedMultifieldFESpace`. Therefore, right now this feature is deactivated in `GridapDistributed`.
2. **[SOLVED] Inconsistency between dof vectors in the FESpace and BlockMatrix:** Our implementation of the `DistributedMultiFieldFESpace` assumes it works with `PVector`s. We would probably like that the free dof vectors become `BlockVector{PVector}` to have consistency with the assembly startegy. This now causes problems with the implementation, which should be eventually looked at. For now, we can live with the inconsistency of having dofs coming from the fe-space be `PVector`s and dof coming from the matrix being `BlockVector{PVector}`. In any case, we would still have to convert between different vector formats due to inconsistencies in the ghosts. 
3. **[SOLVED] `BlockVector` wants it's blocks to be indexable:** This is a minor issue, but the library we are using assumes it's blocks are indexable. This is obviously wrong with `BlockVector{PVector}`, which has forced us to overload most of the `Base` and `LinearAlgebra` functionality for that specific type. This is type piracy, but it's necessary unless some changes are made in `BlockArrays.jl`.

**Comment by amartinhuertas** [comment]
Can we put above the particular commit to which these comments refer to? Thanks!

**Comment by JordiManyer** [comment]
All of the pains have been addressed by the following [PR](https://github.com/gridap/GridapDistributed.jl/pull/128).
