### ISSUE TITLE
Porting GridapSolvers to PArrays v0.3

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/GridapSolvers.jl#30]
Please, before carrying this work take into account the following:

> I have ported RedistributeTools.jl from GridapSolvers.jl to PArrays v0.3 and put it temporarily into GridapP4est.jl. Thus, PLEASE, when porting GridapSolvers.jl to PArrays v0.3 let us start from here. On the other hand, I am positive that the contents of RedistributeTools.jl should go to GridapDistributed.jl. We will also need mock tests, though.

See also https://github.com/gridap/GridapP4est.jl/issues/35 and https://github.com/gridap/GridapP4est.jl/blob/p4est-migration-exploring-non-conformity/src/RedistributeTools.jl for more details

**Comment by JordiManyer** [comment]
@amartinhuertas Yes, I will get on it. I agree with your comments. 

> On the other hand, I am positive that the contents of RedistributeTools.jl should go to GridapDistributed.jl. We will also need mock tests, though.

Concerning this: Should we try to release GridapDistributed v0.3, then patch it with these changes and finally port GridapSolvers? Or should I port GridapSolvers beforehand and then patch both repositories with these changes?

**Comment by amartinhuertas** [comment]
> Concerning this: Should we try to release GridapDistributed v0.3, then patch it with these changes and finally port GridapSolvers? Or should I port GridapSolvers beforehand and then patch both repositories with these changes?

We should tightly coordinate how to proceed with the releases of GridapDistributed and GridapSolvers. I would try that the new releases include both the porting to PArrays v0.3 and the refactoring (i.e., transferring code from GridapSolvers and GridapP4est to GridapDistributed).
