### ISSUE TITLE
JacobiLinearSolvers

### ISSUE THREAD

**Issue by jmartfrut** [gridap/GridapSolvers.jl#61]
Hi @JordiManyer , I think in line 26  of  JacobiLinearSolvers.jl variable "a" should be "A", is this correct?

function Gridap.Algebra.numerical_setup!(ns::JacobiNumericalSetup, A::AbstractMatrix)
  ns.inv_diag .= 1.0 ./ diag(a)
end

Thank you!

**Comment by JordiManyer** [comment]
Yes! It's already in my list. :)
