### ISSUE TITLE
What is a "non-algebraic" solver?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [gridap/GridapSolvers.jl#69]
Do you mean geometric multigrid?

**Comment by JordiManyer** [comment]
Among others, yes.

A non-exhaustive list of what we have/have planned is: 
- Vanka methods
- Subspace correction methods
- Geometric MultiGrid
- Domain Decomposition methods, such as BDDC
- ...

**Comment by PetrKryslUCSD** [comment]
Perhaps this is the "best" name. So what is actually implemented?

**Comment by JordiManyer** [comment]
Yes, all the things in the README are implemented.
