### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by PetrKryslUCSD** [gridap/GridapSolvers.jl#73]
https://gist.github.com/PetrKryslUCSD/284fbe5235809039b8ad3581f0059f55

**Comment by JordiManyer** [comment]
My first comment would be why are you testing `GridapPETSc.jl`, instead of `GridapSolvers.jl`? 

Otherwise, the error seems to be related to MPI. 
- Where are you running your tests? Are you using custom binaries, or artifacts? 
- When using MPI you have to build your project, not only instantiate. Most weird errors go away after building, which is crucial to link all the binaries together.

**Comment by PetrKryslUCSD** [comment]
You are right, I did start by testing GridapSolvers, but the errors below seemed to implicate GridapPETSc. I may be wrong, of course.
This is from the failed test of GridapSolvers:
https://gist.github.com/PetrKryslUCSD/3114a3e5e0a64adc2ba53f14a6c204ca

**Comment by PetrKryslUCSD** [comment]
You are right, I did start by testing GridapSolvers, but the errors below seemed to implicate GridapPETSc. I may be wrong, of course.
This is from the test of 
https://gist.github.com/PetrKryslUCSD/3114a3e5e0a64adc2ba53f14a6c204ca

**Comment by JordiManyer** [comment]
It's an MPI issue, I think. The serial tests are running fine on both cases, but it fails to load the environment when doing the MPI tests. 
Try building the packages first, then run the tests. Instantiating is not enough. I.e 

```julia
using Pkg
Pkg.build()
```

**Comment by PetrKryslUCSD** [comment]
I did what the README suggested. Activ/inst + build.

**Comment by JordiManyer** [comment]
I think MPI.jl might have disabled some mpiexec flags we were using (namely `--allow-run-as-root`), I've pushed a couple changes to `main`. 

Could you please try this: 

```julia
using Pkg
Pkg.add(;name="GridapSolvers",rev="main");
Pkg.build()
```

then **exit and re-start julia**, which allows the links created by `build` to take effect. Once this is done, try testing it. 

I just tested this on our linux cluster, and it seems to run.

**Comment by PetrKryslUCSD** [comment]
Fantastic, all tests pass.

**Comment by JordiManyer** [comment]
Great, I'll do a new minor release and modify our README to make all of this more clear.
