### ISSUE TITLE
Making FGMRESSolver accept nothing as the right preconditioner

### ISSUE THREAD

**Issue by shreyas02** [gridap/GridapSolvers.jl#85]
I am working on a project where I only want to use the left preconditioner using the FGMRES solver. I want this solver to accept nothing as the input for the right preconditioner. Can I create a pull request with these changes?

**Comment by JordiManyer** [comment]
Hi @shreyas02 , I believe FGMRES is not flexible wrt the left preconditioner. I follow the [article from Saad](https://epubs.siam.org/doi/10.1137/0914028), but if you look around (for instance [PETSc](https://petsc.org/main/manualpages/KSP/KSPFGMRES/)) you will see no-one has a left-preconditioned FGMRES. 

At least that is my understanding. Can you provide any reference implementing/showcasing a left-preconditioned flexible FGMRES? If you do, I'll be glad to accept your PR. 

Alternatively, you can use GMRES with only a left-preconditioner. But the preconditioner needs to be static. 
Let me know what you think.

**Comment by shreyas02** [comment]
Hi @JordiManyer, You seem to be correct. I should be using the GMRES solver, at least for now. Thank you!

**Comment by JordiManyer** [comment]
@shreyas02 No worries! Thanks for using the library, and for being willing to contribute!
