### ISSUE TITLE
Preconditioned Richardson Iteration linear solver

### ISSUE THREAD

**Issue by shreyas02** [gridap/GridapSolvers.jl#86]
Hi @JordiManyer, I was wondering why the Preconditioned Richardson iteration solver is not there and only a Richardon smoother is there . I have been using the Preconditioned Richardson method. Perhaps we could add this to the library by creating a pull request?

**Comment by JordiManyer** [comment]
Hi @shreyas02 this is covered by the `LinearSolverFromSmoother` solver. You can do 

```julia
S = LinearSolverFromSmoother(smoother)
```

and it should work. It's not documented, nor tested. I want at some point to draw a clear distinction between smoothers and solvers, and have mappings between the two. This is a first step in that direction.

**Comment by shreyas02** [comment]
Hi @JordiManyer,
Thanks, I had a look at the code. It seems we can't pass arguments such as the tolerance to the solver. It always performs maximum iterations. For a solver, that is not ideal. Should I open a PR to add arguments such as tolerance and logging? 

I understand that this does not make sense for a smoother, so I was thinking of making this argument optional and default setting to 0. So when used as a smoother, it performs n iterations; when used as a solver, it performs iterations until the required tolerance is achieved. 

Also, could you briefly explain the purpose of LinearSolverFromSmoother(smoother)? I see that this is used just for performance benefits by preallocating memory.

**Comment by JordiManyer** [comment]
Closed by #87
